# Generated by Django 5.2.17 on 2026-10-01 19:59

import django.db.models.deletion
import feincms3_filecontent.feincms.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0002_alter_page_options_alter_image_alternative_text_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FileContent",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content_path",
                    models.CharField(
                        help_text="Path of the document relative to the content repository.",
                        max_length=500,
                        validators=[
                            feincms3_filecontent.feincms.models.validate_content_path
                        ],
                        verbose_name="document",
                    ),
                ),
                ("region", models.CharField(max_length=255)),
                ("ordering", models.IntegerField(default=0)),
                (
                    "parent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="pages.page",
                    ),
                ),
            ],
            options={
                "verbose_name": "file content",
                "verbose_name_plural": "file contents",
                "abstract": False,
            },
        ),
    ]
