# Generated by Django 5.2.17 on 2026-10-01 21:49

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="IndexState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("root", models.CharField(blank=True, max_length=500)),
                ("backend", models.CharField(blank=True, max_length=20)),
                ("last_indexed_sha", models.CharField(blank=True, max_length=64)),
                ("last_mode", models.CharField(blank=True, max_length=20)),
                ("indexed_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="ArticleIndex",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("market", models.CharField(max_length=2)),
                ("locale", models.CharField(max_length=10)),
                ("slug", models.CharField(max_length=200)),
                ("title", models.CharField(blank=True, max_length=200)),
                ("status", models.CharField(blank=True, max_length=20)),
                ("category", models.CharField(blank=True, max_length=20)),
                ("publication_date", models.DateTimeField(blank=True, null=True)),
                ("version", models.CharField(max_length=64)),
                ("mtime_ns", models.BigIntegerField(default=0)),
                ("size", models.BigIntegerField(default=0)),
                ("error", models.TextField(blank=True)),
                ("indexed_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "article index entry",
                "verbose_name_plural": "article index",
                "indexes": [
                    models.Index(
                        fields=["market", "locale", "status", "publication_date"],
                        name="content_article_listing",
                    ),
                    models.Index(fields=["category"], name="content_article_category"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("market", "locale", "slug"), name="content_article_key"
                    )
                ],
            },
        ),
    ]
