# Generated by Django 5.2.17 on 2026-10-01 19:53

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models

import feincms3_filecontent.feincms.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Page",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position", models.PositiveIntegerField(db_index=True, default=0)),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="is active"),
                ),
                ("title", models.CharField(max_length=200, verbose_name="title")),
                ("slug", models.SlugField(verbose_name="slug")),
                (
                    "path",
                    models.CharField(
                        blank=True,
                        help_text="Automatically generated by concatenating the parent's path and the slug unless the path is defined manually.",
                        max_length=1000,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Path must start and end with a slash (/).",
                                regex="^/(|.+/)$",
                            )
                        ],
                        verbose_name="path",
                    ),
                ),
                (
                    "static_path",
                    models.BooleanField(
                        default=False, verbose_name="manually define the path"
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="testapp.page",
                        verbose_name="parent",
                    ),
                ),
            ],
            options={
                "verbose_name": "page",
                "verbose_name_plural": "pages",
                "ordering": ["position"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="FileContent",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content_path",
                    models.CharField(
                        help_text="Path of the document relative to the content repository.",
                        max_length=500,
                        validators=[
                            feincms3_filecontent.feincms.models.validate_content_path
                        ],
                        verbose_name="document",
                    ),
                ),
                ("region", models.CharField(max_length=255)),
                ("ordering", models.IntegerField(default=0)),
                (
                    "parent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="testapp.page",
                    ),
                ),
            ],
            options={
                "verbose_name": "file content",
                "verbose_name_plural": "file contents",
                "abstract": False,
            },
        ),
    ]
