# Generated by Django 5.2.17 on 2026-10-01 19:53

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RepositoryState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "branch",
                    models.CharField(
                        max_length=200, unique=True, verbose_name="branch"
                    ),
                ),
                (
                    "last_indexed_sha",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="last indexed SHA"
                    ),
                ),
                (
                    "indexed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="indexed at"
                    ),
                ),
                (
                    "last_sync_mode",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="last sync mode"
                    ),
                ),
                ("last_error", models.TextField(blank=True, verbose_name="last error")),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
            ],
            options={
                "verbose_name": "repository state",
                "verbose_name_plural": "repository states",
            },
        ),
        migrations.CreateModel(
            name="ContentIndex",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "path",
                    models.CharField(max_length=500, unique=True, verbose_name="path"),
                ),
                (
                    "content_type",
                    models.CharField(max_length=100, verbose_name="content type"),
                ),
                (
                    "locale",
                    models.CharField(
                        blank=True, db_index=True, max_length=20, verbose_name="locale"
                    ),
                ),
                (
                    "slug",
                    models.CharField(
                        db_index=True, max_length=200, verbose_name="slug"
                    ),
                ),
                ("title", models.CharField(max_length=500, verbose_name="title")),
                (
                    "metadata",
                    models.JSONField(blank=True, default=dict, verbose_name="metadata"),
                ),
                (
                    "content_hash",
                    models.CharField(max_length=64, verbose_name="content hash"),
                ),
                (
                    "git_sha",
                    models.CharField(blank=True, max_length=64, verbose_name="Git SHA"),
                ),
                (
                    "modified_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="modified at"
                    ),
                ),
                (
                    "indexed_at",
                    models.DateTimeField(auto_now=True, verbose_name="indexed at"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("ok", "ok"), ("invalid", "invalid")],
                        default="ok",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                ("error", models.TextField(blank=True, verbose_name="error")),
            ],
            options={
                "verbose_name": "document",
                "verbose_name_plural": "documents",
                "ordering": ["path"],
                "permissions": [
                    ("edit_document", "Can edit, commit and restore documents"),
                    (
                        "manage_repository",
                        "Can synchronize and rebuild the content index",
                    ),
                ],
                "indexes": [
                    models.Index(
                        fields=["locale", "slug"], name="feincms3_fi_locale_33e07c_idx"
                    )
                ],
            },
        ),
    ]
